### ISSUE TITLE
Can't login in accounts

### ISSUE THREAD

**Issue by pavlosidelov** [MrTuxx/SocialPwned#13]
The docker returns an error like:
[!] Can't Login to Instagram!
for all services in credentials.json, LinkedIn, etc.
the credentials are correct I've checked it several times.

Request example:
sudo docker run -v $(pwd)/credentials.json:/home/.../SocialPwned/credentials.json -v $(pwd)/output:/socialpwned/output -it mrtuxx/socialpwned socialpwned.py --credentials credentials.json --instagram --target-ig pavlosidelov

**Comment by MrTuxx** [comment]
Hello! 

Why do you put that path: /home/.../SocialPwned/credentials.json? The correct path is: /socialpwned/credentials.json. 

That is, with that command what you are saying is what volume you want to put. The parameter on the right is the path inside the docker, in this case /socialpwned/credentials.json (when you build the docker there is a file called credentials.json in that path, clearly empty). 

While in the left parameter you put the path of your machine where is your credentials.json file if you have it in the same directory where you run the command is enough to do $(pwd)/credentials.json, otherwise put your path.

so yo can execute:

`sudo docker run -v $(pwd)/credentials.json:/socialpwned/credentials.json -v $(pwd)/output:/socialpwned/output -it mrtuxx/socialpwned socialpwned.py --credentials credentials.json --instagram --target-ig <dont-disclose-your-insta>`

or:

`sudo docker run -v /home/pavlosidelov/SocialPwned/credentials.json:/socialpwned/credentials.json -v $(pwd)/output:/socialpwned/output -it mrtuxx/socialpwned socialpwned.py --credentials credentials.json --instagram --target-ig <dont-disclose-your-insta>`
