### ISSUE TITLE
Can't login with Instagram

### ISSUE THREAD

**Issue by sopergoras123** [MrTuxx/SocialPwned#17]
Using:
`sudo python3 socialpwned.py --credentials credentials.json --instagram --target-ig ag_soper --pwndb`
I'm getting this:
`[!] Can't Login to Instagram!`

**Comment by MrTuxx** [comment]
Hello,

Verify the following:

1 - That you have entered your password correctly.
2 - That instagram is not asking you for two-factor authentication or verifying the device because you are connecting from an unknown IP address.
3 - That your account is not locked.

I just tested it and it works fine
