### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by BDW87** [MrTuxx/SocialPwned#5]
After the first scan where wasn't any Problems, I got this Error to all Users I search :

[+] Successful login to Instagram!
                                                                             
[-] Searching users with emails :)
Traceback (most recent call last):
  File "/home/kali/Tools/invest/SOCIAL/SocialPwned/socialpwned.py", line 51, in <module>
    run(args)
  File "/home/kali/Tools/invest/SOCIAL/SocialPwned/core/main.py", line 209, in run
    results.extend(instagramParameters(args,ig_username,ig_password))
  File "/home/kali/Tools/invest/SOCIAL/SocialPwned/core/main.py", line 52, in instagramParameters
    temp = instagram.getUserInformation(api,args.target_ig)
  File "/home/kali/Tools/invest/SOCIAL/SocialPwned/core/instagram.py", line 95, in getUserInformation
    if not checkUserVisibility(api,info["user"].get("pk")) and results == []:
KeyError: 'user'

Please tell me how I can fix it ?

Greetz : )

**Comment by MrTuxx** [comment]
Hello,

Tell me the exact command you have executed and verify that your python version is 3.8.

**Comment by BDW87** [comment]
Hi MrTuxx,
the first scan was "... --credentials creds.json --instagram target-ig xxxxxxx --follower-ig --follwings-ig --pwd",
all was fine but after I made a txt-file with touch and give it to the --output parameter it shows me this error.
I had restart Tor, reboot my VM and waiting 2 hours but still the same (with and without --output) ... I used python3.9 but the first scan was fine. Need to figure out how I install 3.8 to my /usr/bin/ to use a virtualvenv, sorry for that Sir I'm a newbie, but when Im done I will test it. : ) 
Greetz

**Comment by MrTuxx** [comment]
I have tried the same command and it works correctly. 

-` python3 socialpwned.py --credentials credentials.json  --instagram --target-ig "name" --followers-ig --followings-ig --output results.txt --pwndb`

That the bug appeared when you added the --output file.txt flag, I don't think it has anything to do with it, basically because the bug appears in a method in which it is collecting information from the user, not writing to the file (saveResults method).

I think it may be because your "target" has many followers and followings and Instagram has blocked you for a while the visibility of users, because you have made several requests. That's why you get the error in the user search. Maybe you should change the delay in the code.

**Comment by BDW87** [comment]
Yeah I think too that the problem  are the request and Instagram blocked them for a while, maybe tomorrow it work again if that the case I will tell you. But thank you so much for answering so fast and take your time for it. <3
